const TMDB = 'https://image.tmdb.org/t/p/w500';

const seedData = {
  peliculas: [
    // Makoto Shinkai — filmografía completa (cortos, OVA y largometrajes)
    {
      titulo: 'El mundo encerrado',
      anio: 1998,
      genero: 'Anime',
      duracionMinutos: 1,
      calificacion: 6.5,
      imagenUrl: `${TMDB}/3Z9JfUMdcEOMyhtyTXwu8FUPaGj.jpg`,
    },
    {
      titulo: 'Otros mundos',
      anio: 1998,
      genero: 'Anime',
      duracionMinutos: 2,
      calificacion: 6.8,
      imagenUrl: `${TMDB}/pHWfz63P72VSVfKggFFJPH2VqmQ.jpg`,
    },
    {
      titulo: 'Ella y su gato',
      anio: 1999,
      genero: 'Anime',
      duracionMinutos: 5,
      calificacion: 7.2,
      imagenUrl: `${TMDB}/wBKfZk6qlyn48vKQNoZs4Thhpwf.jpg`,
    },
    {
      titulo: 'La voz de una distancia lejana',
      anio: 2002,
      genero: 'Anime',
      duracionMinutos: 25,
      calificacion: 7.5,
      imagenUrl: `${TMDB}/mvRqW2z4iBws3CDkCNmojksyr4V.jpg`,
    },
    {
      titulo: 'El lugar prometido en nuestros primeros días',
      anio: 2004,
      genero: 'Anime',
      duracionMinutos: 90,
      calificacion: 7.4,
      imagenUrl: `${TMDB}/xlyJw6WmfLn378oz0ZmI0SYFoGb.jpg`,
    },
    {
      titulo: '5 centímetros por segundo',
      anio: 2007,
      genero: 'Anime',
      duracionMinutos: 63,
      calificacion: 7.6,
      imagenUrl: `${TMDB}/dFipUR6W0y3PPkuVS8gjFd929m2.jpg`,
    },
    {
      titulo: 'Los niños que buscan voces perdidas',
      anio: 2011,
      genero: 'Anime',
      duracionMinutos: 116,
      calificacion: 7.3,
      imagenUrl: `${TMDB}/8RE7Zz9oTzOeMcahqm74AWkOVpV.jpg`,
    },
    {
      titulo: 'El jardín de las palabras',
      anio: 2013,
      genero: 'Anime',
      duracionMinutos: 46,
      calificacion: 7.9,
      imagenUrl: `${TMDB}/mXUCVq3HMtS4Y9IQ8vmEOPyN0vH.jpg`,
    },
    {
      titulo: 'La mirada de alguien',
      anio: 2013,
      genero: 'Anime',
      duracionMinutos: 7,
      calificacion: 7.4,
      imagenUrl: `${TMDB}/m3T8LGmjoMktaiot49Pc8JFFyC6.jpg`,
    },
    {
      titulo: 'Cross Road',
      anio: 2014,
      genero: 'Anime',
      duracionMinutos: 2,
      calificacion: 7.0,
      imagenUrl: `${TMDB}/7gcV3PyrfEuOtBkkuUPJdIMS46V.jpg`,
    },
    {
      titulo: 'Tu nombre',
      anio: 2016,
      genero: 'Anime',
      duracionMinutos: 106,
      calificacion: 8.5,
      imagenUrl: `${TMDB}/q719jXXEzOoYaps6babgKnONONX.jpg`,
    },
    {
      titulo: 'El tiempo contigo',
      anio: 2019,
      genero: 'Anime',
      duracionMinutos: 112,
      calificacion: 8.0,
      imagenUrl: `${TMDB}/qgrk7r1fV4IjuoeiGS5HOhXNdLJ.jpg`,
    },
    {
      titulo: 'Suzume',
      anio: 2022,
      genero: 'Anime',
      duracionMinutos: 122,
      calificacion: 8.1,
      imagenUrl: `${TMDB}/yStW1TXF5s7Tbtu9KjIZEaWl6HL.jpg`,
    },
    // Venezuela
    {
      titulo: 'Libertador Morales, el justiciero',
      anio: 2009,
      genero: 'Comedia',
      duracionMinutos: 106,
      calificacion: 7.2,
      imagenUrl: `${TMDB}/1hCHenBuDu4my6wLUv2s8ijy6au.jpg`,
    },
    {
      titulo: 'Azul y no tan rosa',
      anio: 2012,
      genero: 'Drama',
      duracionMinutos: 114,
      calificacion: 7.8,
      imagenUrl: `${TMDB}/l7FmKyBauwrUCSCMoM7vsbbv6GQ.jpg`,
    },
    {
      titulo: 'Pipí mil, pupú dos lucas',
      anio: 2012,
      genero: 'Comedia',
      duracionMinutos: 65,
      calificacion: 6.5,
      imagenUrl: `${TMDB}/46fbHwljOt7VOzOeFTrUYwYpmZD.jpg`,
    },
    {
      titulo: 'Punto y raya',
      anio: 2004,
      genero: 'Drama',
      duracionMinutos: 105,
      calificacion: 7.0,
      imagenUrl: `${TMDB}/ors5QwSaGZ5MMyhpDlj3FO1MTgC.jpg`,
    },
    {
      titulo: 'Huelepega: Ley de la calle',
      anio: 1999,
      genero: 'Drama',
      duracionMinutos: 105,
      calificacion: 7.6,
      imagenUrl: `${TMDB}/bAk18OmwSmWCLt5Ql3XwZ3Roy9N.jpg`,
    },
  ],
  directores: [
    { nombre: 'Makoto Shinkai', nacionalidad: 'Japón', peliculasDirigidas: 13, premiosOscar: 0 },
    { nombre: 'Elia Schneider', nacionalidad: 'Venezuela', peliculasDirigidas: 8, premiosOscar: 0 },
    { nombre: 'Miguel Ferrari', nacionalidad: 'Venezuela', peliculasDirigidas: 4, premiosOscar: 0 },
    { nombre: 'Efterpi Charalambidis', nacionalidad: 'Venezuela', peliculasDirigidas: 3, premiosOscar: 0 },
    { nombre: 'Enrique y Fernando Bencomo', nacionalidad: 'Venezuela', peliculasDirigidas: 2, premiosOscar: 0 },
  ],
  generos: [
    { nombre: 'Anime', descripcion: 'Animación japonesa con estética y narrativa propias', popularidad: 92, colorHex: '#ec4899' },
    { nombre: 'Drama', descripcion: 'Historias centradas en conflictos emocionales', popularidad: 95, colorHex: '#6366f1' },
    { nombre: 'Comedia', descripcion: 'Entretenimiento ligero con humor', popularidad: 82, colorHex: '#f59e0b' },
    { nombre: 'Ciencia Ficción', descripcion: 'Tecnología avanzada y mundos futuristas', popularidad: 79, colorHex: '#06b6d4' },
    { nombre: 'Fantasía', descripcion: 'Mundos imaginarios y elementos mágicos', popularidad: 85, colorHex: '#8b5cf6' },
  ],
  actores: [
    { nombre: 'Rafael Gil', edad: 45, nacionalidad: 'Venezuela', peliculasDestacadas: 12 },
    { nombre: 'José Gregorio Rivas', edad: 35, nacionalidad: 'Venezuela', peliculasDestacadas: 8 },
    { nombre: 'Ryunosuke Kamiki', edad: 30, nacionalidad: 'Japón', peliculasDestacadas: 28 },
    { nombre: 'Mone Kamishiraishi', edad: 26, nacionalidad: 'Japón', peliculasDestacadas: 18 },
    { nombre: 'Edgardo Román', edad: 40, nacionalidad: 'Venezuela', peliculasDestacadas: 10 },
  ],
  resenas: [
    { pelicula: 'Tu nombre', autor: 'Ana García', calificacion: 10, comentario: 'Obra maestra del anime contemporáneo' },
    { pelicula: 'Azul y no tan rosa', autor: 'Carlos Ruiz', calificacion: 9, comentario: 'Primer Goya iberoamericano para Venezuela' },
    { pelicula: 'Huelepega: Ley de la calle', autor: 'Laura Méndez', calificacion: 9, comentario: 'Retrato duro y necesario de Caracas' },
    { pelicula: 'Punto y raya', autor: 'Miguel Torres', calificacion: 8, comentario: 'Amistad imposible en la frontera' },
    { pelicula: 'Pipí mil, pupú dos lucas', autor: 'Sofía López', calificacion: 7, comentario: 'Comedia negra con mucha personalidad' },
  ],
};

module.exports = { seedData };
